# Generated by Django 4.1.7 on 2023-02-19 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="reset_password_token",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="reset_password_token_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
