# Generated by Django 4.1.7 on 2023-02-21 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Signary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("signid", models.CharField(max_length=6, unique=True)),
                ("wellsid", models.CharField(blank=True, max_length=10, null=True)),
                ("frequency", models.IntegerField(default=0)),
            ],
            options={"verbose_name_plural": "Signary",},
        ),
    ]
