# Generated by Django 4.1.7 on 2023-02-21 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inscription", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="signary",
            name="link",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="signary",
            name="signid",
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
