# Generated by Django 4.1.7 on 2023-02-21 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inscription", "0002_signary_link_alter_signary_signid"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seqid", models.CharField(max_length=8, unique=True)),
                ("seq_in_num", models.CharField(max_length=150)),
                ("links", models.CharField(blank=True, max_length=700)),
                ("cisi_id", models.CharField(blank=True, max_length=10, null=True)),
                ("wells_id", models.CharField(blank=True, max_length=5, null=True)),
                (
                    "artefact_type",
                    models.CharField(blank=True, max_length=25, null=True),
                ),
                (
                    "material_type",
                    models.CharField(blank=True, max_length=25, null=True),
                ),
                (
                    "field_symbol",
                    models.CharField(blank=True, max_length=25, null=True),
                ),
                (
                    "excavation_number",
                    models.CharField(blank=True, max_length=25, null=True),
                ),
                ("area", models.CharField(blank=True, max_length=25, null=True)),
                ("remark", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
