# Generated by Django 4.1.7 on 2023-02-21 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inscription", "0003_sequence"),
    ]

    operations = [
        migrations.AddField(
            model_name="sequence",
            name="site",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
