# Generated by Django 4.1.7 on 2023-02-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inscription", "0004_sequence_site"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sequence",
            name="links",
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name="signary",
            name="link",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
